name: "Build Openwrt Image in Github CI With Javascript"
author: "Sirherobrine23"
description: "Create Snapshot images in Github Actions"
inputs:
  URL:
    description: 'Git Repository URL'
    required: false
    default: 'https://git.openwrt.org/openwrt/openwrt.git'

  BRANCH:
    description: 'Git Repository Branch'
    required: false
    default: 'master'

  MOREPACKAGE:
    description: 'Apt package to add to use in build'
    required: false
    default: ''

  FEEDS_FILE:
    description: 'Openwrt Feed Repository File'
    required: false
    default: 'feeds.conf.default'

  CONFIG:
    description: 'Openwrt Build File'
    required: false
    default: '.config'

  NGROK_TOKEN:
    description: 'Ngrok http web server'
    required: false
    default: ''
    
  NGROK_TIME:
    description: 'Ngrok http web server'
    required: false
    default: '5m'

  P1:
    description: 'File Bash Script for execute before feed Update'
    required: false
    default: 'p1.sh'

  P2:
    description: 'File Bash Script for execute before feed Update'
    required: false
    default: 'p2.sh'

runs:
  using: 'node12'
  pre: 'setup.js'
  main: 'copiler.js'
  post: 'sleep.js'

branding:
  icon: 'code'
  color: 'gray-dark'