name: 'Openwrt Build CI'
author: 'Sirherobrine23'
description: 'Create Snapshot images in Github Actions'
inputs:
  URL:
    description: 'Git Repository URL'
    required: false
    default: 'https://git.openwrt.org/openwrt/openwrt.git'

  BRANCH:
    description: 'Git Repository Branch'
    required: false
    default: 'master'

  MOREPACKAGE:
    description: 'Apt package to add to use in build'
    required: false
    default:

  FEEDS_FILE:
    description: 'Openwrt Feed Repository File'
    required: false
    default: 'feeds.conf.default'

  CONFIG:
    description: 'Openwrt Build File'
    required: false
    default: '.config'

  P1:
    description: 'File Bash Script for execute before feed Update'
    required: false
    default: 'p1.sh'

  P2:
    description: 'File Bash Script for execute before feed Update'
    required: false
    default: 'p2.sh'
runs:
  using: "composite"
  name: Install And Copiler
  steps:
    - name: Packages Install
      run: |
        echo "Atualizando Os Repositorios APT"
        sudo apt-get -qq update &> Apt-Log.txt
        sudo apt install -y curl &> Apt-Log.txt
        sudo apt purge -y *golang* *node* *android* *google* *mysql* *java* *openjdk* &> Apt-Log.txt
        echo "Instalando Os Pacotes Adicionais: ${{ inputs.MOREPACKAGE }}"
        sudo apt -y install dos2unix git zip rsync mkisofs ${{ inputs.MOREPACKAGE }} $(curl -fsSL https://raw.githubusercontent.com/P3TERX/openwrt-list/master/depends-ubuntu-2004) &> Apt-Log.txt
        sudo apt-get -qq autoremove --purge &> Apt-Log.txt
        # Remove Swap
        echo "Removendo os Swaps"
        sudo swapoff -a
        sudo rm -rfv /mnt/swap*
        sudo chown $USER:$USER /mnt
        sudo chmod 777 /mnt
      shell: bash
      env:
        DEBIAN_FRONTEND: 'noninteractive'

    - run: |
        bash $GITHUB_ACTION_PATH/Build.sh
      env:
        URL: ${{ inputs.URL }}
        BRANCH: ${{ inputs.BRANCH }}
        FEEDS_FILE: ${{ inputs.FEEDS_FILE }}
        CONFIG: ${{ inputs.CONFIG }}
        P1: ${{ inputs.P1 }}
        P2: ${{ inputs.P2 }}
      shell: bash


branding:
  icon: 'code'
  color: 'gray-dark'

# ${{ inputs.P1 }}